application: myapp
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /search
  script: api.py
  login: admin

- url: /respond
  script: api.py
  login: admin

- url: /ask
  script: api.py


